name: ESLint Lint File

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "repository"
        required: true
        type: string

      branch:
        description: "branch"
        required: true
        type: string

      relative_file_path:
        description: "relative file path"
        required: true
        type: string

      eslint_rule:
        description: "eslint rule (example: quotes)"
        required: true
        type: string

      node_version:
        description: "node version"
        default: "20.19.4"
        required: true
        type: string

jobs:
  eslint-lint-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint File
        run: |
          NODE_OPTIONS="--max-old-space-size=16384" \
          npx eslint \
          "${{ inputs.relative_file_path }}" \
          --rule '${{ inputs.eslint_rule }}: error' \
          --max-warnings=241 \
          --cache --cache-location=node_modules/.cache/eslint
